FROM mysql:5.7 as builder

# That file does the DB initialization but also runs mysql daemon, by removing the last line it will only init
RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

# needed for intialization
ENV MYSQL_DATABASE dongtai_webapi
ENV MYSQL_ROOT_PASSWORD dongtai-iast

ADD https://huoqi-public.oss-cn-beijing.aliyuncs.com/iast/sql/sca.sql /docker-entrypoint-initdb.d/sca-0.sql
ADD https://huoqi-public.oss-cn-beijing.aliyuncs.com/iast/sql/rule.sql /docker-entrypoint-initdb.d/rule.sql
ADD https://huoqi-public.oss-cn-beijing.aliyuncs.com/iast/sql/sca-20220516-170.sql.tar /docker-entrypoint-initdb.d/sca-20220516-170.sql.tar

COPY db.sql /docker-entrypoint-initdb.d/

COPY update-*release*.sql /docker-entrypoint-initdb.d/

RUN cd /docker-entrypoint-initdb.d/ && tar -xvf sca-20220516-170.sql.tar && mv sca-20220516-170.sql update-20220515-release-1.7.0-sca.sql && rm -rf sca-20220516-170.sql.tar && chmod 777 /docker-entrypoint-initdb.d -R

RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci", "--datadir", "/initialized-db"]

FROM mysql:5.7
ENV MYSQL_DATABASE dongtai_webapi
ENV MYSQL_ROOT_PASSWORD dongtai-iast


COPY --from=builder /initialized-db /var/lib/mysql

COPY update-*release*.sql /sql/

CMD [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci" ]
