SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE `dongtai_webapi`.`auth_group_routes` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_aql_info` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_aql_info` MODIFY COLUMN `vul_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '漏洞编号 汇总' AFTER `id`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info` MODIFY COLUMN `vul_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '漏洞标题' AFTER `vul_number`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info` MODIFY COLUMN `safe_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '安全版本' AFTER `vul_title`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info` MODIFY COLUMN `latest_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '最新版本' AFTER `safe_version`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info` MODIFY COLUMN `source_license` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '开源许可证' AFTER `availability`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info` MODIFY COLUMN `vul_type_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '漏洞类型名称' AFTER `license_risk`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info` MODIFY COLUMN `aql` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `vul_type_name`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info` MODIFY COLUMN `hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'aql hash' AFTER `level_id`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info2` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_aql_info2` MODIFY COLUMN `vul_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '漏洞编号 汇总' AFTER `id`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info2` MODIFY COLUMN `vul_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '漏洞标题' AFTER `vul_number`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info2` MODIFY COLUMN `safe_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '安全版本' AFTER `vul_title`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info2` MODIFY COLUMN `latest_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '最新版本' AFTER `safe_version`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info2` MODIFY COLUMN `source_license` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '开源许可证' AFTER `availability`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info2` MODIFY COLUMN `vul_type_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '漏洞类型名称' AFTER `license_risk`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info2` MODIFY COLUMN `aql` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `vul_type_name`;
ALTER TABLE `dongtai_webapi`.`iast_aql_info2` MODIFY COLUMN `hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'aql hash' AFTER `level_id`;
ALTER TABLE `dongtai_webapi`.`iast_asset_aggr` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_asset_aggr` MODIFY COLUMN `package_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '第三方包名' AFTER `id`;
ALTER TABLE `dongtai_webapi`.`iast_asset_aggr` MODIFY COLUMN `signature_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '签名值' AFTER `package_name`;
ALTER TABLE `dongtai_webapi`.`iast_asset_aggr` MODIFY COLUMN `version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '当前版本' AFTER `signature_value`;
ALTER TABLE `dongtai_webapi`.`iast_asset_aggr` MODIFY COLUMN `safe_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '安全版本' AFTER `version`;
ALTER TABLE `dongtai_webapi`.`iast_asset_aggr` MODIFY COLUMN `last_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '最新版本' AFTER `safe_version`;
ALTER TABLE `dongtai_webapi`.`iast_asset_aggr` MODIFY COLUMN `license` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '许可证' AFTER `project_count`;
ALTER TABLE `dongtai_webapi`.`iast_asset_aggr` MODIFY COLUMN `language` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '语言' AFTER `license`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `search_title` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '为搜索引擎准备的标题' AFTER `vul_name`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `vul_detail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '漏洞详情' AFTER `search_title`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `license` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '漏洞标题+编号(fulltext)' AFTER `level_id`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `package_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `aql`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `package_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '组件hash' AFTER `package_name`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `package_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '组件版本' AFTER `package_hash`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `package_fix_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '当前漏洞修复版本' AFTER `package_version`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `package_safe_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '组件安全版本' AFTER `package_fix_version`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `package_latest_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '组件最新版本' AFTER `package_safe_version`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `package_language` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '组件语言 JAVA\\GO' AFTER `package_latest_version`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul` MODIFY COLUMN `cve_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '漏洞CVE编号' AFTER `have_poc`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul_relation` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul_type` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul_type` MODIFY COLUMN `cwe_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'cwe编号' AFTER `id`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul_type` MODIFY COLUMN `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '漏洞类型名称' AFTER `cwe_id`;
ALTER TABLE `dongtai_webapi`.`iast_asset_vul_type_relation` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_circuit_configs` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_circuit_configs` MODIFY COLUMN `name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `dongtai_webapi`.`iast_circuit_configs` MODIFY COLUMN `metric_types` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `name`;
ALTER TABLE `dongtai_webapi`.`iast_circuit_configs` MODIFY COLUMN `targets` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `metric_types`;
ALTER TABLE `dongtai_webapi`.`iast_circuit_metrics` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_circuit_metrics` MODIFY COLUMN `measure` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `metric_type`;
ALTER TABLE `dongtai_webapi`.`iast_circuit_metrics` MODIFY COLUMN `value` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `opt`;
ALTER TABLE `dongtai_webapi`.`iast_circuit_targets` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_circuit_targets` MODIFY COLUMN `value` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `opt`;
ALTER TABLE `dongtai_webapi`.`iast_http_method` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_message` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_message` MODIFY COLUMN `message` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' AFTER `id`;
ALTER TABLE `dongtai_webapi`.`iast_message` MODIFY COLUMN `relative_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' AFTER `message`;
ALTER TABLE `dongtai_webapi`.`iast_message_type` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_message_type` MODIFY COLUMN `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' AFTER `id`;
ALTER TABLE `dongtai_webapi`.`iast_third_party_service` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_third_party_service` MODIFY COLUMN `port` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '端口' AFTER `agent_id`;
ALTER TABLE `dongtai_webapi`.`iast_third_party_service` MODIFY COLUMN `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '地址' AFTER `port`;
ALTER TABLE `dongtai_webapi`.`iast_third_party_service` MODIFY COLUMN `service_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '服务类型' AFTER `address`;
ALTER TABLE `dongtai_webapi`.`iast_vul_all` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_vul_all` MODIFY COLUMN `aggregation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '聚合条件' AFTER `last_time`;
ALTER TABLE `dongtai_webapi`.`iast_vul_log` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_vul_log` MODIFY COLUMN `msg` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '日志详情' AFTER `id`;
ALTER TABLE `dongtai_webapi`.`iast_vul_recheck_payload` COLLATE = utf8mb4_general_ci;
ALTER TABLE `dongtai_webapi`.`iast_vul_recheck_payload` MODIFY COLUMN `value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL AFTER `id`;

SET FOREIGN_KEY_CHECKS=1;
