name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
          
      - name: SQL LINT 
        run: |
          sudo apt install npm -y
          sudo npm i -g sql-lint 
          sql-lint . trailing-whitespace || true

      - name: Build Mysql only schema to local 
        working-directory: ./mysql
        run: |
          docker build -t registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-test:0.1.${{github.run_number}} .
          docker tag registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-test:0.1.${{github.run_number}} registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-test:latest
      
      - name: Push to DockerHub mysql
        run: | 
          docker push registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-test:0.1.${{github.run_number}}
          docker push registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-test:latest

      - name: Build Mysql only schema to local 
        working-directory: ./redis
        run: |
          docker build -t  registry.cn-beijing.aliyuncs.com/secnium/dongtai-redis-saas-test:0.1.${{github.run_number}} .
          docker tag registry.cn-beijing.aliyuncs.com/secnium/dongtai-redis-saas-test:0.1.${{github.run_number}} registry.cn-beijing.aliyuncs.com/secnium/dongtai-redis-saas-test:latest

      - name: Push to DockerHub redis
        run: | 
          docker push registry.cn-beijing.aliyuncs.com/secnium/dongtai-redis-saas-test:0.1.${{github.run_number}}
          docker push registry.cn-beijing.aliyuncs.com/secnium/dongtai-redis-saas-test:latest

