name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
          
      - name: SQL LINT 
        run: |
          sudo apt install npm -y
          sudo npm i -g sql-lint 
          sql-lint . trailing-whitespace || true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: ./mysql/
          push: true
          tags: |
            registry.cn-hongkong.aliyuncs.com/secnium/dongtai-mysql-test:latest
            registry.cn-hongkong.aliyuncs.com/secnium/dongtai-mysql-test:1.0.${{github.run_number}}

      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST_DATA }}
        with:
          args: |
            find .github/deploy/deploy-dongtai-mysql-test-max.yaml -type f -exec sed -i 's/VERSION/1.0.${{github.run_number}}/g' {} \;
            ls .github/deploy/deploy-dongtai-mysql-test-max.yaml | xargs -I {} kubectl apply -f {}
            kubectl rollout -n iast-test-max restart statefulset redis

