name: Build And Push DongTai Base Image To Aliyun Repo

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DONGTAI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DONGTAI_DOCKERHUB_TOKEN }}
          
      - name: SQL LINT 
        run: |
          sudo apt install npm -y
          sudo npm i -g sql-lint 
          sql-lint . trailing-whitespace || true

      - name: Build and push MySql
        uses: docker/build-push-action@v2
        with:
          context: ./mysql
          push: true
          tags: | 
            registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-test:0.1.${{github.run_number}}
      
      - name: Build and push Redis
        uses: docker/build-push-action@v2
        with:
          context: ./redis
          push: true
          tags: |
            registry.cn-beijing.aliyuncs.com/secnium/dongtai-redis-saas-test:0.1.${{github.run_number}}

      - name: Push to DockerHub
        run: | 
          docker push dongtai/dongtai-mysql-unittest:0.1.${{github.run_number}}
          docker push dongtai/dongtai-mysql-unittest:latest
