name: Build sca

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: self-hosted
    strategy:
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
          
      #- name: SQL LINT 
      #  run: |
      #    sudo apt install npm -y
      #    sudo npm i -g sql-lint 
      #    sql-lint . trailing-whitespace || true

      - name: Build Mysql only schema to local 
        working-directory: ./mysql
        run: |
          docker build -t registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-sca-test:0.1.${{github.run_number}} . -f Dockerfile-sca
          docker tag registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-sca-test:0.1.${{github.run_number}} registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-sca-test:latest
      
      - name: Push to DockerHub
        run: | 
          docker push registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-sca-test:0.1.${{github.run_number}}
          docker push registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-sca-test:latest
          docker rmi -f registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-sca-test:0.1.${{github.run_number}}
          docker rmi -f registry.cn-beijing.aliyuncs.com/secnium/dongtai-mysql-saas-sca-test:latest


